spring:
  datasource:
    # PostgreSQL Custom ENUM 타입을 String으로 주고받으려면 Hibernate에 "stringtype=unspecified" 옵션이 필요
    url: jdbc:postgresql://localhost:5432/yonsei_shuttle?currentSchema=yonsei_shuttle&stringtype=unspecified
    username: ${DB_USERNAME:shuttle}
    password: ${DB_PASSWORD:shuttle1234}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.yonsei.shuttle: INFO
    root: WARN